version: 2.1

jobs:
  run-scan:
    docker:
      - image: ubuntu:20.04

    steps:
      - checkout
      - run:
          name: Install NodeJS and nexploit-cli
          environment:
            DEBIAN_FRONTEND: 'noninteractive'
          command: |
            apt -y update
            apt-get -y install libnode-dev node-gyp libssl-dev
            apt-get -y install nodejs npm
            npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
      - run:
          name: Start Nexploit Scan 🏁
          command: |
            SCAN_ID=$(nexploit-cli scan:run                                                 \
            --test csrf dom_xss xss header_security secret_tokens open_buckets                 \
            --name "💎 BrokenCrystals for CircleCI" \
            --crawler https://brokencrystals.com/  \
            --token $BRIGHTSEC_TOKEN)
            printf "Scan id is: $SCAN_ID"
            echo "export SCAN_ID=\"$SCAN_ID\"" >> $BASH_ENV
            
      - run:
          name: Output scan URL
          command: |
            printf "Scan was started with ID https://brightsec.app/scans/${SCAN_ID}"
      - run:
          name: Wait for issues ⏳
          command: |
            nexploit-cli scan:polling               \
            --interval 30s                        \
            --timeout 10m                         \
            --token $BRIGHTSEC_TOKEN               \
            --breakpoint high_issue ${SCAN_ID}
      - run:
          name: Stop Scan on Failure
          command: nexploit-cli scan:stop --token $BRIGHTSEC_TOKEN $SCAN_ID
          when: on_fail

workflows:
  run-scan-workflow:
    jobs:
      - run-scan
